/* export const activeListeningPhrases = [
    "Та ти що, так цікаво!",
    "Серйозно? Це дуже цікаво!",
    "Невже? Розкажи більше!",
    "Ого, це щось новеньке!",
    "Вау, це вражає!",
    "Нічого собі, це круто!",
    "Це неймовірно!",
    "Правда? Це захоплююче!",
    "Це дуже цікаво, продовжуй!",
    "Оце так, неочікувано!",
]; */

export const activeListeningPhrases = [
    "Wirklich? Das ist interessant!",
    "Ernsthaft? Das ist sehr spannend!",
    "Echt? Erzähl mir mehr!",
    "Wow, das ist etwas Neues!",
    "Das ist beeindruckend!",
    "Wirklich? Das ist cool!",
    "Das ist unglaublich!",
    "Wirklich? Das ist faszinierend!",
    "Das ist sehr interessant, erzähl weiter!",
    "Das ist unerwartet!",
];

/* export const jokes = [
    "Чому вчителі не йдуть у відпустку на Місяць? Бо на Місяці немає атмосфери!",
    "Чому програмісти не ходять у спортзал? Вони бояться зависнути на тренажерах!",
    "Якщо дерево впаде в лісі, і ніхто цього не побачить, чи потрібно йому надсилати запит на підтримку?",
    "Чому комп'ютери ніколи не втомлюються? Вони просто завантажують енергію з розетки!",
    "Чому математики не люблять море? Їм важко знайти квадратний корінь із хвилі!",
    "Чому пірати завжди з радістю співають? Бо в них завжди є «Аррр» у репертуарі!",
    "Що говорить риба, коли плаває в солоній воді? «Що за день! Я знову солений!»",
    "Якщо курка перейде дорогу двічі, це буде подвійна переправа?",
    "Чому кухарі завжди в хорошому настрої? Бо їх завжди щось смажить!",
    "Що робить комар, коли хоче поласувати? Він замовляє «кусачий» сніданок!",
    "Чому лікарі завжди такі обережні? Бо вони знають, що кожен діагноз – це відповідальність!",
    "Чому зебри не можуть грати в хованки? Їх смужки завжди видають!",
    "Чому актори завжди посміхаються перед виходом на сцену? Вони знають, що сміх – це найкраща репетиція!",
    "Що говорить сир, коли його фотографують? «Сир!»",
    "Чому бджоли завжди зайняті? Вони просто не можуть втриматися від солодких справ!",
    "Чому на уроках історії ніколи не буває нудно? Бо там завжди багато подій!",
    "Що робить кіт, коли бачить іншу кішку на вулиці? Він влаштовує «мяу» дискусію!",
    "Чому кавуни такі популярні влітку? Вони знають, як охолодити день!",
    "Чому астрономи завжди дивляться в небо? Бо вони шукають нові зірки для своїх колекцій!",
    "Що робить кіт, коли йому сумно? Він завжди знаходить щось для розваги, навіть якщо це просто папірець!",
    "Чому птахи завжди щебечуть? Вони просто обговорюють новини!",
    "Чому у фотографів завжди хороші кадри? Вони знають, коли натискати кнопку!",
    "Що робить банан, коли він хоче відпочити? Він просто знімає свою шкірку!",
    "Чому лікарі завжди питають про симптоми? Бо їм потрібно скласти правильний пазл!",
    "Що робить кіт, коли бачить мишу? Влаштовує «сирний» рейд!",
    "Чому літаки завжди літають високо? Бо вони люблять подорожувати вище хмар!",
    "Чому диригенти завжди рухають руками? Вони малюють музику у повітрі!",
    "Що робить слон, коли він хоче заховатися? Він стає дуже тихим і намагається змішатися з натовпом!",
    "Чому ведмеді завжди сплять взимку? Бо вони накопичують сили для весняних пригод!",
    "Що говорить комп'ютер, коли зависає? «Дайте мені хвилинку, я обмірковую!»",
    "Чому люди люблять морозиво? Бо це єдине, що може розтанути і залишити щасливу посмішку!",
    "Чому літаки завжди мають два крила? Вони знають, що баланс – це запорука успіху!",
    "Що робить кавун, коли бачить ніж? Він трохи напружується, але залишається свіжим!",
    "Чому феї завжди літають? Бо їх крила створені для польотів, а не для сидіння!",
    "Що говорить йога-мат, коли на нього ступають? «Залишайтеся зі мною, я вас підтримую!»",
    "Чому у гусей завжди гарний настрій? Вони просто гуснуть від сміху!",
    "Що робить осел, коли бачить сходи? Він піднімає вуха і готовий до нових підйомів!",
    "Чому кішки люблять молоко? Вони знають, що це їхній улюблений напій!",
    "Чому зірки завжди сяють вночі? Бо це їхній час бути на сцені!",
    "Що робить корова, коли бачить зелену траву? Вона готується до «зеленого» обіду!",
    "Чому книжки завжди тримають в секреті свій кінець? Вони хочуть, щоб ви дочитали до останньої сторінки!",
    "Чому дощ любить падати? Бо він знає, що кожна крапля – це маленький подарунок для землі!",
    "Що говорить ведмідь, коли прокидається після сплячки? «Ще п’ять хвилин, будь ласка!»",
    "Чому морські їжаки завжди такі колючі? Вони просто хочуть захистити свої секрети!",
    "Що робить черепаха, коли бачить дорогу? Вона завжди планує свій маршрут заздалегідь!",
    "Чому карасі завжди такі спокійні? Вони знають, що вода – їхня стихія!",
    "Що робить місяць, коли сонце заходить? Він виходить на свою нічну прогулянку!",
];
 */
export const jokes = [
    "Warum können Geister so schlecht lügen? Weil man durch sie hindurchsehen kann.",
    "Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock.",
    "Warum haben Geheimagenten immer einen Regenschirm? Weil es immer einen Tropfen gibt.",
    "Was macht ein Pirat am Computer? Er drückt die Enter-Taste.",
    "Warum können Geister keine Lügen erzählen? Weil man durch sie hindurchsieht.",
    "Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock.",
    "Was sagt ein Schaf zum anderen, wenn es etwas vergessen hat? 'Ich hab's verdrängt!'",
    "Warum gehen Uhren nicht zum Essen? Weil sie keine Zeit haben.",
    "Was macht ein Keks unter einem Baum? Krümel!",
    "Warum können Skelette nicht tanzen? Weil ihnen der nötige Schwung fehlt.",
    "Was macht ein Pirat im Winter? Er sitzt am Kamin und singt 'Schatz, bring den Rum her!'",
    "Warum können Geister keine Geheimnisse bewahren? Weil sie immer durchsichtig sind.",
    "Wie nennt man ein helles Mammut? Hellmut.",
    "Warum können Skelette nicht kämpfen? Weil sie keine Muskeln haben.",
    "Warum sind Gespenster schlechte Fußballspieler? Weil sie Angst vor dem Ball haben.",
    "Was ist grün und stellt Fragen? Ein Fragensalat.",
    "Warum haben Elefanten rote Augen? Damit sie sich besser im Kirschbaum verstecken können.",
    "Was macht ein Pirat im Garten? Er sät seine Beute.",
    "Warum können Geister kein Tennis spielen? Weil sie keinen Körper haben.",
    "Was macht ein Schaf am Computer? Es sucht im Web.",
    "Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock.",
    "Warum können Skelette nicht schwimmen? Weil sie keine Haut haben.",
    "Was macht ein Pirat mit zwei Beinen? Er geht auf einen Kumpel los.",
    "Warum sind Gespenster schlechte Köche? Weil sie keinen Geschmack haben.",
    "Was ist weiß und rollt den Berg hoch? Eine Lawine mit Heimweh.",
    "Warum können Geister nicht boxen? Weil sie keine Faust machen können.",
    "Wie nennt man eine Katze, die alle Geheimnisse verrät? Eine Petze.",
    "Warum haben Geister Angst vor dem Licht? Weil sie schüchtern sind.",
    "Was macht ein Bär, wenn er zu viel Schokolade isst? Er bekommt Schoko-Bären.",
    "Warum können Skelette keine Liebe finden? Weil sie kein Herz haben.",
    "Was macht ein Pirat, wenn er eine Abkürzung nimmt? Er kürzt seinen Schatz.",
    "Warum können Gespenster nicht Fahrrad fahren? Weil sie durch den Wind pfeifen.",
    "Was ist orange und läuft durch den Wald? Eine Wanderine.",
    "Warum können Geister nicht singen? Weil sie keinen Körper haben.",
    "Was ist braun und hüpft durch den Wald? Ein Kastanienmännchen auf einem Trampolin.",
    "Warum sind Geister immer so kühl? Weil sie durch Wände gehen.",
    "Wie nennt man einen Bumerang, der nicht zurückkommt? Einen Stock.",
    "Was ist grün und läuft durch den Wald? Ein Brokkoli auf Wandertag.",
    "Warum können Skelette keine Opern singen? Weil sie keine Stimmbänder haben.",
    "Was macht ein Pirat im Dschungel? Er sucht seinen Schatz.",
    "Warum sind Geister schlechte Tänzer? Weil sie keinen Rhythmus haben.",
    "Was ist braun und klebt an den Schuhen? Ein Kaugummi im Wald.",
    "Warum können Geister nicht kochen? Weil sie keine Hände haben.",
    "Wie nennt man eine Kuh, die ein Musikinstrument spielt? Eine Kuhzert.",
    "Warum können Geister keine Freunde finden? Weil sie durch Wände gehen.",
    "Was macht ein Pirat im Supermarkt? Er plündert die Regale.",
    "Warum können Geister keine Briefe schreiben? Weil sie keinen Stift halten können.",
    "Was ist rot und schlecht für die Zähne? Ein Backstein.",
    "Warum haben Geister keinen Spaß? Weil sie immer so ernst sind.",
];
